# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/statistics.normalization.ipynb (unless otherwise specified).

__all__ = ['normalize_L212']

# Cell
import numpy as np

def normalize_L212(X):

    n = X.shape[0]
    norms = np.linalg.norm(X, axis = tuple([0,1]))#.sum(axis = )
    gammas = np.sqrt(n) / norms
    X_norm = np.einsum('i b p, p -> i b p', X, gammas)

    return(X_norm)