# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"position_to_torsion": "atomgeom.features.ipynb",
         "position_to_distances": "atomgeom.features.ipynb",
         "position_to_planarangle": "atomgeom.features.ipynb",
         "get_grads4": "atomgeom.features.ipynb",
         "get_features": "atomgeom.features.ipynb",
         "load_data": "exec.get_features.ipynb",
         "get_features_parallel": "exec.get_features.ipynb",
         "parse_args": "exec.get_features.ipynb",
         "get_rigid_ethanol_data": "simulations.rigidethanol.ipynb",
         "get_234_indices": "utils.utils.ipynb",
         "get_atoms4_full": "utils.utils.ipynb",
         "get_atoms3_full": "utils.utils.ipynb",
         "data_stream_custom_range": "utils.utils.ipynb"}

modules = ["atomgeom/features.py",
           "exec/get_features.py",
           "simulations/rigidethanol.py",
           "utils/utils.py"]

doc_url = "https://{user}.github.io/montlake/"

git_url = "https://github.com/{user}/montlake/tree/{branch}/"

def custom_doc_links(name): return None
