# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_stream_custom_range": "utils.utils.ipynb",
         "position_to_torsion": "atomgeom.features.ipynb",
         "position_to_distances": "atomgeom.features.ipynb",
         "position_to_planarangle": "atomgeom.features.ipynb",
         "get_grads1": "atomgeom.features.ipynb",
         "get_grads2": "atomgeom.features.ipynb",
         "get_grads3": "atomgeom.features.ipynb",
         "get_features2": "atomgeom.features.ipynb",
         "load_data": "exec.get_features.ipynb",
         "get_features_parallel": "exec.get_features.ipynb",
         "parse_args": "exec.get_features.ipynb",
         "get_geom": "geometry.geometry.ipynb",
         "get_rm_tangent_sel": "geometry.geometry.ipynb",
         "get_nbr_wts": "geometry.geometry.ipynb",
         "get_wlpca_tangent_sel": "geometry.geometry.ipynb",
         "RiemannianManifold": "geometry.geometry.ipynb",
         "TangentBundle": "geometry.geometry.ipynb",
         "get_grads_pullback": "gradients.estimate.ipynb",
         "GradientGroupLasso": "optimization.gradientgrouplasso.ipynb",
         "get_sr_lambda_parallel": "optimization.gradientgrouplasso.ipynb",
         "batch_stream": "optimization.gradientgrouplasso.ipynb",
         "width": "plotting.plotting.ipynb",
         "plot_reg_path_ax_lambdasearch_customcolors_names": "plotting.plotting.ipynb",
         "get_rigid_ethanol_data": "simulations.rigidethanol.ipynb",
         "get_swiss_roll_data": "simulations.swissroll.ipynb",
         "get_dx_g_full": "simulations.swissroll.ipynb",
         "get_swiss_roll_gradients": "simulations.swissroll.ipynb",
         "normalize_L212": "statistics.normalization.ipynb",
         "get_detected_values2d": "utils.replicates.ipynb",
         "get_support_indices2d": "utils.replicates.ipynb",
         "Replicate": "utils.replicates.ipynb",
         "get_234_indices": "utils.utils.ipynb",
         "get_atoms4_full": "utils.utils.ipynb",
         "get_atoms3_full": "utils.utils.ipynb"}

modules = ["atomgeom/features.py",
           "exec/get_features.py",
           "geometry/geometry.py",
           "gradients/estimate.py",
           "optimization/gradientgrouplasso.py",
           "plotting/plotting.py",
           "simulations/rigidethanol.py",
           "simulations/swissroll.py",
           "statistics/normalization.py",
           "utils/replicates.py",
           "utils/utils.py"]

doc_url = "https://{user}.github.io/montlake/"

git_url = "https://github.com/{user}/montlake/tree/{branch}/"

def custom_doc_links(name): return None
